language: python

python:
  - "3.5"

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install -e .

before_script:
  - flake8 .

script:
  - py.test --cov=shanghai --cov-config .coveragerc ./tests/

after_success:
  - coverage xml
  - coveralls

notifications:
  # email: false
  irc:
    channels:
      - "chat.freenode.net#chireiden"
    on_success: change
    skip_join: true
    # use_notice: true
