language: python

python:
  - "3.5"

env:
  - TOXENV=py35
  - TOXENV=flake8
  - TOXENV=mypy

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  # email: false
  irc:
    channels:
      - "chat.freenode.net#chireiden"
    on_success: change
    skip_join: true
    # use_notice: true
