language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install flake8
  - pip install -e .

before_script:
  - flake8 .

script:
  - py.test --cov=shanghai --cov-config .coveragerc ./tests/

after_success:
  - coverage xml
  - coveralls
