language: python

python:
  - "3.6"

env:
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=mypy
  - TOXENV=pylint

branches:
  except:
    - /^wip\//

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  # email: false
  irc:
    channels:
      - "chat.freenode.net#chireiden"
    on_success: change
    skip_join: true
    # use_notice: true
